name: Cypress Tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6
        continue-on-error: true
        with:
          spec: cypress/e2e/cucumber-bdd-test/dashboard.feature
          build: npm run build
          start: npm start
          browser: chrome